POST http://localhost:8080/api/definitions
Content-Type: application/json

{
    "entryWord": "tradition",
    "partOfSpeech": "n.",
    "plural": false,
    "definition": "Peer pressure from dead people.",
    "originalQuote": "",
    "attributedTo": "Jesse Applegate",
    "source_id": "",
    "source_date": "20221003",
    "source_description": "",
    "other_sources": "",
    "definitionType": "",
    "keywords": "",
    "categories": "",
    "source": "",
    "context": "",
    "game": "N"
}
