POST http://localhost:8080/api/sources
Content-Type: application/json

{
    "description": "",
    "author": "Jesse Applegate",
    "publishedDate": "20321003",
    "citation": "Applegate, Jesse. <i>The Wise Words of JM Applegate.</i> MIT Press, 2032.",
    "notes": "This was actually told to me by Jesse directly."
}
