# https://medium.com/boca-code/deploying-an-express-api-to-google-app-engine-ac7a188c6608
runtime: nodejs16
env: standard
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
